// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/google/notification": {
            "post": {
                "description": "post notification webhook",
                "tags": [
                    "Google"
                ],
                "summary": "Notification",
                "parameters": [
                    {
                        "description": "content",
                        "name": "content",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/google.NotificationStruct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.JSONResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.JSONResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "google.Incident": {
            "type": "object",
            "properties": {
                "condition_name": {
                    "description": "条件的显示名",
                    "type": "string"
                },
                "ended_at": {
                    "description": "结束时间",
                    "type": "integer"
                },
                "observed_value": {
                    "description": "触发值",
                    "type": "string"
                },
                "policy_name": {
                    "description": "策略名称",
                    "type": "string"
                },
                "resource_display_name": {
                    "description": "资源展示名称",
                    "type": "string"
                },
                "resource_type_display_name": {
                    "description": "监控资源类型的显示名",
                    "type": "string"
                },
                "scoping_project_id": {
                    "description": "托管指标范围的项目 ID",
                    "type": "object"
                },
                "started_at": {
                    "description": "开始时间",
                    "type": "integer"
                },
                "summary": {
                    "type": "string"
                },
                "threshold_value": {
                    "description": "阈值",
                    "type": "string"
                },
                "url": {
                    "description": "突发事件的 Google Cloud Console 网址",
                    "type": "string"
                }
            }
        },
        "google.NotificationStruct": {
            "type": "object",
            "properties": {
                "incident": {
                    "$ref": "#/definitions/google.Incident"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "handlers.JSONResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "v1.0.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Alerting Webhook",
	Description: "This is a os remote executor orchestration script interface.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
